import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { supabase } from "@/lib/supabase";
import SlateCarousel from "./components/SlateCarousel";

/* =========================================================
   SHOW DATA — swap in real content here
   ========================================================= */
export const shows = [
  {
    id: "ngl",
    title: "Not Gonna Lie with Kylie Kelce",
    category: "CULTURE",
    categoryColor: "#A60AFF",
    tagline: "No filter. No landing page. Just sport.",
    description: "Placeholder — replace with show description.",
    specs: "WEEKLY · ~30 MIN · VIDEO",
    season: "SEASON 2 · 2026",
    videoPath: null as string | null,
    oneSheetPath: null as string | null,
    demo: "18–30 · Female-Leaning",
    thumbnailPath: "/thumbnails/ngl.jpg",
    slateImagePath: "/assets/Images/Slate/Slides BG_Not Gonna Lie.png",
    detailImagePath: "/assets/Images/Slate/Detail_Not Gonna Lie 2.jpg",
    accoladeLogoPath: "/assets/accolades/3x/webby@3x.png",
    accolades: [
      "2026|PODCAST OF|THE YEAR",
      "2026|BEST NEW PODCAST,|ENTERTAINMENT",
      "2026|BEST PARTNERSHIP|OR COLLABORATION",
      "2026|BEST INDIVIDUAL|EPISODE",
    ],
    talent: "Kylie Kelce",
    detailTopics: ["Entertainment", "Motherhood", "Women in Sports"],
    detailDescription: "Armed with one mic and zero f*cks, Kylie is ready to open up — on her own terms. Join her as she sets the record straight on gossip and speaks her truths on topics like modern parenting, social media trends, women in sports and more.",
    detailDemographics: "18-30\nFEMALE-LEANING",
    detailCadence: "WEEKLY\nMON / THU",
    detailFormat: "Celebrity/personal-story talk show",
    detailPartnerships: "KEY PARTNERSHIPS AND EPISODES",
    youtubeUrl: "https://www.youtube.com/@nglwithkylie",
    audioUrl: "https://open.spotify.com/show/0RgXbSGGmwpzAyeLHbDqUD",
    audience: {
      followers: "3.7M",
      monthlyViews: "140M",
      monthlyDownloads: "625K",
      genderSkew: "86/14 Female",
      persona: "Kelce Mom — Female, 25–44, married with kids, upper-middle income; leans Caucasian and is interested in entertainment",
      quickHits: ["Modern motherhood", "Philanthropy", "Real talk"],
      guestExamples: ["Michelle Obama", "Kelly Clarkson", "Ms. Rachel", "Chelsea Handler"],
      ages: [
        { label: "13–17", pct: 2.21 },
        { label: "18–24", pct: 6.20 },
        { label: "25–34", pct: 34.67 },
        { label: "35–44", pct: 24.55 },
        { label: "45–54", pct: 13.62 },
        { label: "55–64", pct: 9.98 },
        { label: "65+", pct: 8.63 },
      ],
      hhi100k: "65.7%",
      usShare: "78%",
      races: [
        { label: "Caucasian", pct: 50.4 },
        { label: "Hispanic", pct: 5.4 },
        { label: "African American", pct: 3.6 },
        { label: "Asian", pct: 2.8 },
        { label: "Middle Eastern", pct: 1.6 },
        { label: "Native American", pct: 0.2 },
        { label: "Other", pct: 36.0 },
      ],
      topGeos: ["California 9.0%", "Texas 6.8%", "Pennsylvania 5.3%", "Florida 4.9%", "New York 4.6%"],
      devices: [
        { label: "Mobile", pct: 49.4 },
        { label: "TV", pct: 27.1 },
        { label: "Computer", pct: 14.4 },
        { label: "Tablet", pct: 9.1 },
      ],
      avgWatchTime: "22 min avg YouTube watch time",
      viewerBehavior: { new: 24.8, casual: 35.2, regular: 40.0 },
      interests: ["Country 47%", "American football 44%", "News 40%", "Rock 40%", "Reality TV 27%"],
      audienceOverlap: ["New Heights", "Good Hang", "The YOYOYO Podcast"],
    },
  },
  {
    id: "bad-friends",
    title: "Bad Friends",
    category: "COMEDY",
    categoryColor: "#FFC421",
    tagline: "Placeholder — replace with tagline.",
    description: "Comedians Bobby Lee and Andrew Santino bring their goofy, blue, and spontaneous humor to the Bad Friends podcast every week, landing themselves consistently at the top of the charts. Intentionally apolitical, built on their friendship and chemistry, this show attracts viewers from all walks of life for accessible comedy featuring some of today's top comedic voices.",
    detailDescription: "Comedians Bobby Lee and Andrew Santino bring their goofy, blue, and spontaneous humor to the Bad Friends podcast every week, landing themselves consistently at the top of the charts. Intentionally apolitical, built on their friendship and chemistry, this show attracts viewers from all walks of life for accessible comedy featuring some of today's top comedic voices.",
    specs: "Placeholder — replace with specs.",
    detailFormat: "Two-host comedy conversation podcast",
    season: "2026",
    videoPath: null as string | null,
    oneSheetPath: null as string | null,
    demo: "18–35 · Mixed",
    thumbnailPath: "/thumbnails/big-bro.jpg",
    slateImagePath: "/assets/Images/Slate/Slides BG_Bad Friends.jpg",
    detailImagePath: "/assets/Images/Slate/Detail_Bad Friends.jpg",
    talent: "Andrew Santino & Bobby Lee",
    youtubeUrl: "https://www.youtube.com/@BadFriends",
    audioUrl: "https://open.spotify.com/show/3gaGfrqgnVqUBNDdtv5p3S",
    audience: {
      followers: "5M",
      monthlyViews: "38M",
      monthlyDownloads: "14.7M",
      genderSkew: "85/15 Male",
      ages: [
        { label: "18–24", pct: 7.60 },
        { label: "25–34", pct: 47.90 },
        { label: "35–44", pct: 31.60 },
        { label: "45–54", pct: 8.70 },
      ],
      hhi100k: "58%",
      races: [
        { label: "White/Caucasian", pct: 68.3 },
        { label: "Hispanic", pct: 15.1 },
        { label: "African American", pct: 6.7 },
        { label: "Asian", pct: 6.9 },
      ],
      interests: ["Sports", "MMA", "Comedy", "Rap & Hip Hop", "Gaming"],
    },
  },
  {
    id: "whiskey-ginger",
    title: "Whiskey Ginger",
    category: "LIFESTYLE",
    categoryColor: "#FFC421",
    tagline: "Drinks, stories, and the people who make them.",
    description: "Comedian Andrew Santino interviews friends in and out of the entertainment industry as they reflect on deviant stories of their past; while sipping whiskey.",
    specs: "WEEKLY · ~55 MIN · AUDIO + VIDEO",
    detailFormat: "Comedy interview/conversation show",
    season: "SEASON 5 · 2026",
    videoPath: null as string | null,
    oneSheetPath: null as string | null,
    demo: "21–45 · Mixed",
    thumbnailPath: "/thumbnails/whiskey-ginger.jpg",
    slateImagePath: "/assets/Slides BG_Santino.jpg",
    detailImagePath: "/assets/Images/Slate/Detail_Whiskey Ginger.jpg",
    talent: "Andrew Santino",
    youtubeUrl: "https://www.youtube.com/@AndrewSantinoWhiskeyGinger",
    audioUrl: "https://open.spotify.com/show/2QoIpuCjh332VOeDYxLr3A",
    audience: {
      followers: "2M",
      monthlyViews: "5M",
      monthlyDownloads: "230K",
      genderSkew: "85/15 Male",
      persona: "Comedy Bro — Male, 25–44, middle-to-upper income, interested in comedy, sports and gaming",
      quickHits: ["Comedy", "Celebrity & entertainment", "Lifestyle"],
      guestExamples: ["John Cena", "Eric Andre", "Shane Gillis", "Benny Blanco"],
      ages: [
        { label: "13–17", pct: 0.13 },
        { label: "18–24", pct: 5.30 },
        { label: "25–34", pct: 44.46 },
        { label: "35–44", pct: 36.33 },
        { label: "45–54", pct: 10.44 },
        { label: "55–64", pct: 2.29 },
        { label: "65+", pct: 0.99 },
      ],
      hhi100k: "58.7%",
      usShare: "80%",
      races: [
        { label: "Caucasian", pct: 46.4 },
        { label: "Hispanic", pct: 9.7 },
        { label: "African American", pct: 4.3 },
        { label: "Asian", pct: 3.8 },
        { label: "Middle Eastern", pct: 1.4 },
        { label: "Native American", pct: 0.3 },
      ],
      topGeos: ["California 9.2%", "Texas 4.5%", "Wisconsin 3.7%", "Illinois 3.0%", "Florida 2.8%"],
      devices: [
        { label: "Mobile", pct: 54.4 },
        { label: "TV", pct: 25.6 },
        { label: "Computer", pct: 15.4 },
        { label: "Tablet", pct: 4.1 },
      ],
      avgWatchTime: "32.2 min avg watch · 27.2 min avg listen",
      viewerBehavior: { new: 31.1, casual: 40.2, regular: 28.7 },
      interests: ["Comedy 25%", "Sport 22%", "Gaming 21%", "Sports 19%", "Rap & hip hop 19%"],
      audienceOverlap: ["Bad Friends", "Theo Von", "PowerfulJRE"],
    },
  },
  {
    id: "open-thoughts",
    title: "Open Thoughts",
    category: "INTERVIEW",
    categoryColor: "#0AC2FF",
    tagline: "Real conversations. No script.",
    description: "Nothing's scripted. Nothing's safe. On Open Thoughts, Funny Marco sits down with some of the biggest names in the game for the most unpredictable conversations on the internet.",
    specs: "BIWEEKLY · ~50 MIN · AUDIO + VIDEO",
    detailFormat: "Celebrity interview show",
    season: "SEASON 1 · 2026",
    videoPath: null as string | null,
    oneSheetPath: null as string | null,
    demo: "25–44 · Mixed",
    thumbnailPath: "/thumbnails/open-thoughts.jpg",
    slateImagePath: "/assets/Images/Slate/Slides BG_Open Thoughts.jpg",
    talent: "Funny Marco",
    youtubeUrl: "https://www.youtube.com/@OpenThoughts0",
    audioUrl: "https://open.spotify.com/show/7AwnOVezHIfHVbNVINNlQL",
    audience: {
      followers: "1.2M",
      monthlyViews: "19M",
      monthlyDownloads: "10K",
      genderSkew: "60/40 Male",
      persona: "Culture Voice — Male-leaning, 25–34, predominantly African American, single, driven by hip-hop & R&B",
      quickHits: ["Comedy", "Celebrity & entertainment", "Hip-hop"],
      guestExamples: ["Nicki Minaj", "Kevin Hart", "Keke Palmer", "Druski"],
      ages: [
        { label: "13–17", pct: 0.60 },
        { label: "18–24", pct: 11.40 },
        { label: "25–34", pct: 43.30 },
        { label: "35–44", pct: 30.70 },
        { label: "45–54", pct: 10.60 },
        { label: "55–64", pct: 2.50 },
        { label: "65+", pct: 0.90 },
      ],
      hhi100k: "10%",
      usShare: "90%",
      races: [
        { label: "African American", pct: 75 },
        { label: "White/Caucasian", pct: 19 },
        { label: "Hispanic", pct: 4 },
        { label: "Asian", pct: 2 },
      ],
      topGeos: ["Texas 9.0%", "Georgia 6.5%", "California 6.2%", "Illinois 6.2%", "Florida 5.6%"],
      devices: [
        { label: "TV", pct: 58.1 },
        { label: "Mobile", pct: 30.9 },
        { label: "Computer", pct: 7.0 },
        { label: "Tablet", pct: 3.9 },
      ],
      avgWatchTime: "12 min avg watch · 5 min avg listen",
      viewerBehavior: { new: 38.5, casual: 49.4, regular: 12.1 },
      interests: ["Rap & Hip Hop 38%", "R&B 36%", "Basketball 30%", "American Football 26%", "Soul 22%"],
      audienceOverlap: ["DeenTheGreat", "Revolt", "Deen N AB Updates"],
    },
  },
  {
    id: "power-hour",
    title: "Power Hour",
    category: "LIFESTYLE",
    categoryColor: "#69EDE9",
    tagline: "Placeholder — replace with tagline.",
    description: "This ain't your average fitness show. Here, we champion three things: Strength, pushing boundaries, and looking good while doing it. Ilona Maher brings some of the biggest names in sports and entertainment into the gym to test their limits.",
    specs: "Placeholder — replace with specs.",
    detailFormat: "Fitness and celebrity conversation talk show",
    season: "2026",
    videoPath: null as string | null,
    oneSheetPath: null as string | null,
    demo: "18–35 · Mixed",
    thumbnailPath: "/thumbnails/open-thoughts.jpg",
    slateImagePath: "/assets/Images/Slate/Slides BG_Power Hour.jpg",
    talent: "Ilona Maher",
    youtubeUrl: "https://www.youtube.com/@HouseofMaher",
    audioUrl: null as string | null,
  },
  {
    id: "almost-athletes",
    title: "Almost Athletes",
    category: "COMEDY",
    categoryColor: "#D12670",
    tagline: "They never made the cut. They never stopped trying.",
    description: "Almost Athletes with Dude Perfect is (almost) a sports podcast. Co-hosted by Garrett Hilbert and Sparky, with the rest of the Dudes, their wives, and the DP crew popping in throughout the week. Sports takes, celebrity guests, athlete interviews, fan voicemails, and the kind of chaos you'd expect from the Dude Perfect family.",
    specs: "WEEKLY · ~60 MIN · AUDIO + VIDEO",
    detailFormat: "Weekly sports recap, hot takes, and guest conversations",
    season: "SEASON 2 · 2026",
    videoPath: null as string | null,
    oneSheetPath: null as string | null,
    demo: "18–34 · Male-Leaning",
    thumbnailPath: "/thumbnails/almost-athletes.jpg",
    slateImagePath: "/assets/Images/Slate/Slides BG_Almost Athletes.jpg",
    detailNavTone: "dark",
    talent: "Dude Perfect",
    youtubeUrl: "https://www.youtube.com/@almostathletes",
    audioUrl: "https://open.spotify.com/show/55gaQm31JIbp6td7QtYsPU",
    audience: {
      followers: "162K",
      monthlyViews: "12M",
      monthlyDownloads: "80K",
      genderSkew: "81/19 Male",
      persona: "Family Sports Fan — Male, 18–34 with meaningful teen reach; highest household income in the slate; married with kids",
      quickHits: ["Sports & entertainment", "Lifestyle", "Family", "Friendship"],
      guestExamples: ["Steph Curry", "Peyton Manning", "Caitlin Clark", "Tom Brady"],
      ages: [
        { label: "13–17", pct: 9.52 },
        { label: "18–24", pct: 21.37 },
        { label: "25–34", pct: 29.00 },
        { label: "35–44", pct: 23.69 },
        { label: "45–54", pct: 12.97 },
        { label: "55–64", pct: 2.37 },
        { label: "65+", pct: 1.03 },
      ],
      hhi100k: "66.6%",
      usShare: "86%",
      races: [
        { label: "Caucasian", pct: 48.9 },
        { label: "Hispanic", pct: 4.1 },
        { label: "African American", pct: 3.6 },
        { label: "Asian", pct: 2.0 },
        { label: "Middle Eastern", pct: 0.9 },
        { label: "Native American", pct: 0.3 },
      ],
      topGeos: ["Texas 10.1%", "California 5.5%", "Florida 4.0%", "Ohio 3.8%", "Pennsylvania 3.5%"],
      devices: [
        { label: "Mobile", pct: 32.1 },
        { label: "TV", pct: 46.9 },
        { label: "Computer", pct: 12.8 },
        { label: "Tablet", pct: 8.3 },
      ],
      avgWatchTime: "30 min avg watch · 22 min avg listen",
      viewerBehavior: { new: 36.1, casual: 46.5, regular: 17.5 },
      interests: ["American football 52%", "Sport 49%", "Christian & gospel 35%", "Basketball 34%", "News 34%"],
      audienceOverlap: ["Dude Perfect Outdoors", "The FRDI Show", "DP Interns"],
    },
  },
  {
    id: "so-true",
    title: "So True",
    category: "COMEDY",
    categoryColor: "#0AC2FF",
    tagline: "Placeholder — replace with tagline.",
    description: "A weekly podcast from beloved gay comedian Caleb Hearon. Basically, just getting into it and sorting it all out and kind of identifying what’s really real.",
    specs: "Placeholder — replace with specs.",
    detailFormat: "Comedy and pop-culture guest conversation",
    season: "2026",
    videoPath: null as string | null,
    oneSheetPath: null as string | null,
    demo: "18–34 · Mixed",
    thumbnailPath: "/thumbnails/so-true.jpg",
    slateImagePath: "/assets/Images/Slate/Slides BG_So True.jpg",
    accoladeGroups: [
      {
        logoPath: "/assets/accolades/3x/iHeart@3x.png",
        logoAlt: "iHeartRadio",
        accolades: ["2026|BEST PODCAST|HOST"],
      },
      {
        logoPath: "/assets/accolades/3x/Queerties@3x.png",
        logoAlt: "The Queerties",
        accolades: ["2026|PODCAST OF THE|YEAR NOMINEE"],
      },
      {
        logoPath: "/assets/accolades/3x/webby@3x.png",
        logoAlt: "The Webby Awards",
        accolades: ["2025|OFFICIAL WEBBY|HONOREE"],
      },
    ],
    talent: "Caleb Hearon",
    youtubeUrl: "https://www.youtube.com/@sooootruepod",
    audioUrl: "https://open.spotify.com/show/3EgXpWE5vz6JkRtjhenVOU",
    audience: {
      followers: "581K",
      monthlyViews: "22M",
      monthlyDownloads: "667K",
      genderSkew: "70/28 Female",
      persona: "So Truer — Female-leaning, notably younger skew, urban, into music and comedy",
      quickHits: ["Comedy & entertainment", "Pop culture", "Lifestyle"],
      guestExamples: ["Bob the Drag Queen", "Trixie Mattel", "Brittany Broski", "Hannah Berner"],
      ages: [
        { label: "13–17", pct: 0.58 },
        { label: "18–24", pct: 13.72 },
        { label: "25–34", pct: 40.44 },
        { label: "35–44", pct: 12.71 },
        { label: "45–54", pct: 3.41 },
        { label: "55–64", pct: 1.23 },
        { label: "65+", pct: 0.51 },
      ],
      hhi100k: "58.4%",
      usShare: "62%",
      races: [
        { label: "Caucasian", pct: 46.4 },
        { label: "Hispanic", pct: 8.7 },
        { label: "African American", pct: 6.2 },
        { label: "Asian", pct: 4.2 },
        { label: "Middle Eastern", pct: 1.6 },
        { label: "Native American", pct: 0.2 },
      ],
      topGeos: ["California 13.5%", "Texas 7.4%", "New York 6.1%", "Florida 4.5%", "Illinois 3.8%"],
      devices: [
        { label: "Mobile", pct: 52.8 },
        { label: "TV", pct: 26.2 },
        { label: "Computer", pct: 15.2 },
        { label: "Tablet", pct: 5.8 },
      ],
      avgWatchTime: "25 min avg YouTube watch time",
      viewerBehavior: { new: 34.8, casual: 34.5, regular: 30.6 },
      interests: ["Alternative/Indie rock 45%", "LGBTQ+ 45%", "Pop 41%", "Rock 41%", "Comedy 32%"],
      audienceOverlap: ["Royal Court", "cassieopeeyah", "Ziwe"],
    },
  },
  {
    id: "wingmen",
    title: "Wingmen",
    category: "SPORTS",
    categoryColor: "#0BDD65",
    tagline: "Placeholder — replace with tagline.",
    description: "Welcome to Wingmen, hosted by NHL brothers Matthew & Brady Tkachuk. Your all-access pass into the world of hockey, brotherhood, and behind-the-scenes stories you won’t hear anywhere else.",
    specs: "Placeholder — replace with specs.",
    detailFormat: "Hockey-focused sports talk podcast",
    season: "2026",
    videoPath: null as string | null,
    oneSheetPath: null as string | null,
    demo: "18–35 · Male-Leaning",
    thumbnailPath: "/thumbnails/wingmen.jpg",
    slateImagePath: "/assets/Images/Slate/Slides BG_Wingmen.jpg",
    talent: "Matthew & Brady Tkachuk",
    youtubeUrl: "https://www.youtube.com/@Wingmenpod",
    audioUrl: "https://open.spotify.com/show/0phWiahC5nLC7azlkhe8hh",
    audience: {
      followers: "162K",
      monthlyViews: "14M",
      monthlyDownloads: "60K",
      genderSkew: "87/12 Male",
      persona: "Hockey Loyalist — Male, 25–44; highest income of the slate; notably cross-border with many Canadian viewers; married and hockey-first",
      quickHits: ["Hockey talk", "NHL insights", "Sports fandom", "Family"],
      guestExamples: ["NHL teammates", "NHL legends", "Celebrity fans", "Notable personalities"],
      ages: [
        { label: "13–17", pct: 1.09 },
        { label: "18–24", pct: 11.09 },
        { label: "25–34", pct: 42.48 },
        { label: "35–44", pct: 26.09 },
        { label: "45–54", pct: 11.35 },
        { label: "55–64", pct: 5.55 },
        { label: "65+", pct: 2.32 },
      ],
      hhi100k: "67.0%",
      usShare: "59%",
      races: [
        { label: "Caucasian", pct: 46.3 },
        { label: "Hispanic", pct: 5.0 },
        { label: "African American", pct: 3.7 },
        { label: "Asian", pct: 2.8 },
        { label: "Middle Eastern", pct: 2.2 },
        { label: "Native American", pct: 0.5 },
      ],
      topGeos: ["Ottawa, ON 3.2%", "Toronto, ON 2.5%", "Calgary, AB 1.4%", "New York 0.9%", "Montreal, QC 0.8%"],
      devices: [
        { label: "Mobile", pct: 45.4 },
        { label: "TV", pct: 32.6 },
        { label: "Computer", pct: 16.4 },
        { label: "Tablet", pct: 5.6 },
      ],
      avgWatchTime: "27.4 min avg watch · 21.3 min avg listen",
      viewerBehavior: { new: 32.2, casual: 55.8, regular: 12.0 },
      interests: ["Hockey 63%", "Sport 56%", "American football 38%", "Baseball 33%", "Golf 31%"],
      audienceOverlap: ["TFS", "Game Script NHL", "sdpn"],
    },
  },
  {
    id: "7pm-brooklyn",
    title: "7PM in Brooklyn",
    category: "SPORTS",
    categoryColor: "#FF5C35",
    tagline: "Placeholder — replace with tagline.",
    description: "Hoops, culture, and conversation collide at 7PM. Carmelo Anthony sits with a rotating all star crew of The Kid Mero, Rudy Gay, Monica McNutt, and Kazeem Famuyide to tap into the game, the culture, and the stories that shape both.",
    specs: "Placeholder — replace with specs.",
    detailFormat: "Basketball and culture conversation show",
    season: "2026",
    videoPath: null as string | null,
    oneSheetPath: null as string | null,
    demo: "18–35 · Male-Leaning",
    thumbnailPath: "/thumbnails/7pm-brooklyn.jpg",
    slateImagePath: "/assets/Images/Slate/Slides BG_7PM in Brooklyn.jpg",
    accoladeLogoPath: "/assets/accolades/3x/webby@3x.png",
    accolades: [
      "2026|BEST SPORTS|SHOW FINALIST",
      "2026|BEST FEATURED|GUEST NOMINEE",
    ],
    talent: "Carmelo Anthony",
    youtubeUrl: "https://www.youtube.com/@7PMinBrooklyn",
    audioUrl: "https://open.spotify.com/show/4sEy5p87mJ002F3NGsKIpq",
    audience: {
      followers: "1.7M",
      monthlyViews: "44M",
      monthlyDownloads: "1.1M",
      genderSkew: "89/11 Male",
      persona: "Culture Fan — Male, 25–44, one of the slate's most ethnically diverse audiences, basketball- and hip-hop-obsessed",
      quickHits: ["Sports & entertainment", "Lifestyle", "Music", "Fashion"],
      guestExamples: ["Spike Lee", "Sue Bird", "Issa Rae", "Jayson Tatum"],
      ages: [
        { label: "13–17", pct: 0.19 },
        { label: "18–24", pct: 7.25 },
        { label: "25–34", pct: 37.20 },
        { label: "35–44", pct: 31.42 },
        { label: "45–54", pct: 15.18 },
        { label: "55–64", pct: 6.05 },
        { label: "65+", pct: 2.65 },
      ],
      hhi100k: "50.0%",
      usShare: "80%",
      races: [
        { label: "Caucasian", pct: 31.4 },
        { label: "African American", pct: 15.7 },
        { label: "Hispanic", pct: 9.5 },
        { label: "Asian", pct: 4.0 },
        { label: "Middle Eastern", pct: 1.1 },
        { label: "Native American", pct: 0.3 },
      ],
      topGeos: ["New York 10.6%", "California 8.1%", "Texas 7.4%", "Florida 5.8%", "Georgia 5.3%"],
      devices: [
        { label: "Mobile", pct: 41.6 },
        { label: "TV", pct: 48.5 },
        { label: "Computer", pct: 7.3 },
        { label: "Tablet", pct: 2.6 },
      ],
      avgWatchTime: "24 min avg YouTube watch time",
      viewerBehavior: { new: 26.9, casual: 40.5, regular: 32.7 },
      interests: ["Sport 57%", "Basketball 57%", "Rap & hip hop 52%", "Sports 44%", "American football 44%"],
      audienceOverlap: ["Club 520 Podcast", "The Arena", "Nightcap"],
    },
  },
  {
    id: "big-bro",
    title: "Big Bro",
    category: "COMEDY",
    categoryColor: "#D12670",
    tagline: "Placeholder — replace with tagline.",
    description: "Cudi invites his favorite people in culture and entertainment to come kick it. He puts you on to dope s**t, and taps into the real journey behind his and his guests' biggest successes.",
    specs: "Placeholder — replace with specs.",
    detailFormat: "Music and culture interview/commentary show",
    season: "2026",
    videoPath: null as string | null,
    oneSheetPath: null as string | null,
    demo: "18–34 · Mixed",
    thumbnailPath: "/thumbnails/big-bro.jpg",
    slateImagePath: "/assets/Images/Slate/Slides BG_Big Bro.jpg",
    talent: "Kid Cudi",
    youtubeUrl: "https://www.youtube.com/@BigBroCudi",
    audioUrl: "https://open.spotify.com/show/015FnGMuczOXnpFEMbrlu5",
    audience: {
      followers: "62K",
      monthlyViews: "17M",
      monthlyDownloads: "40K",
      genderSkew: "77% Male",
      persona: "Young Culture Creative — Male, 25–34, largely single, highly college-educated, lower household income, driven by music/entertainment/culture",
      quickHits: ["Celebrity & entertainment", "Music", "Art", "Lifestyle"],
      guestExamples: ["Kylie Jenner", "Jenna Ortega", "Timothée Chalamet", "Tyler James Williams"],
      ages: [
        { label: "13–17", pct: 4.25 },
        { label: "18–24", pct: 14.62 },
        { label: "25–34", pct: 54.66 },
        { label: "35–44", pct: 19.62 },
        { label: "45–54", pct: 4.56 },
        { label: "55–64", pct: 1.48 },
        { label: "65+", pct: 0.81 },
      ],
      hhi100k: "12%",
      usShare: "72%",
      races: [
        { label: "White/Caucasian", pct: 56.25 },
        { label: "Hispanic", pct: 19.89 },
        { label: "African American", pct: 22.77 },
        { label: "Asian", pct: 1.09 },
      ],
      topGeos: ["California 16%", "Texas 8.5%", "New York 5.6%", "Florida 5.2%", "Georgia 3.3%"],
      devices: [
        { label: "Mobile", pct: 45.8 },
        { label: "TV", pct: 35.4 },
        { label: "Computer", pct: 13.1 },
        { label: "Tablet", pct: 5.6 },
      ],
      avgWatchTime: "16.4 min avg YouTube watch time",
      viewerBehavior: { new: 72.6, casual: 27.4, regular: 0 },
      interests: ["Rap & hip hop 39.6%", "Sport 25.7%", "Music 24.4%", "American football 24.1%", "Basketball 23.7%"],
      audienceOverlap: ["JoeandJada", "soseriuzradio", "Druski"],
    },
  },
  {
    id: "house-of-maher",
    title: "House of Maher",
    category: "COMEDY",
    categoryColor: "#FFC421",
    tagline: "Placeholder — replace with tagline.",
    description: "A relatable, hilarious talk show led by Ilona Maher and her sisters Olivia and Adrianna, covering pop culture, social media, dating stories and wholesome conversations with guests.",
    detailDescription: "A relatable, hilarious talk show led by Ilona Maher and her sisters Olivia and Adrianna, covering pop culture, social media, dating stories and wholesome conversations with guests.",
    specs: "Placeholder — replace with specs.",
    detailFormat: "Pop-culture and lifestyle talk show",
    season: "2026",
    videoPath: null as string | null,
    oneSheetPath: null as string | null,
    demo: "18–35 · Mixed",
    thumbnailPath: "/thumbnails/house-of-maher.jpg",
    slateImagePath: "/assets/Images/Slate/Slides BG_House of Maher.jpg",
    detailNavTone: "dark",
    talent: "Ilona Maher",
    youtubeUrl: "https://www.youtube.com/@HouseofMaher",
    audioUrl: "https://open.spotify.com/show/5kQkbgxHPgvBc0wcb9qhNK",
    audience: {
      followers: "230K",
      monthlyViews: "50M",
      monthlyDownloads: "106K",
      genderSkew: "83/17 Female",
      persona: "Maher Millennial — Female, 25–34, college-leaning millennial with strong household income, drawn to music and pop culture",
      quickHits: ["Pop culture", "Women empowerment", "Lifestyle", "Sports"],
      guestExamples: ["Alan Bersten", "Malala Yousafzai", "Mamrie Hart", "Kylie Kelce"],
      ages: [
        { label: "13–17", pct: 0.70 },
        { label: "18–24", pct: 15.15 },
        { label: "25–34", pct: 46.42 },
        { label: "35–44", pct: 16.93 },
        { label: "45–54", pct: 9.94 },
        { label: "55–64", pct: 7.04 },
        { label: "65+", pct: 4.08 },
      ],
      hhi100k: "64.7%",
      usShare: "76%",
      races: [
        { label: "Caucasian", pct: 49.6 },
        { label: "Hispanic", pct: 6.0 },
        { label: "African American", pct: 3.8 },
        { label: "Asian", pct: 3.2 },
        { label: "Middle Eastern", pct: 1.5 },
        { label: "Native American", pct: 0.2 },
      ],
      topGeos: ["California 9.5%", "Texas 6.3%", "New York 4.0%", "Florida 4.0%", "Pennsylvania 3.0%"],
      devices: [
        { label: "Mobile", pct: 52.9 },
        { label: "TV", pct: 22.8 },
        { label: "Computer", pct: 15.9 },
        { label: "Tablet", pct: 8.5 },
      ],
      avgWatchTime: "22 min avg YouTube watch time",
      viewerBehavior: { new: 52.8, casual: 36.3, regular: 10.9 },
      interests: ["Rock 32%", "Country 31%", "News 31%", "Pop 30%", "Alternative/Indie rock 30%"],
      audienceOverlap: ["Not Gonna Lie", "Good Hang", "hudcon central"],
    },
  },
  {
    id: "my-momma-told-me",
    title: "My Momma Told Me",
    category: "COMEDY",
    categoryColor: "#0AC2FF",
    tagline: "Placeholder — replace with tagline.",
    description: "Comedians Langston Kerman and David Gborie take a deep dive into the most exciting, groundbreaking and sometimes problematic Black conspiracy theories. They'll have guests cover silly conspiracies, scary conspiracies and conspiracies they learned from that uncle who used to wear jeans when he went swimming in the public pool.",
    detailDescription: "Comedians Langston Kerman and David Gborie take a deep dive into the most exciting, groundbreaking and sometimes problematic Black conspiracy theories. They'll have guests cover silly conspiracies, scary conspiracies and conspiracies they learned from that uncle who used to wear jeans when he went swimming in the public pool.",
    specs: "Placeholder — replace with specs.",
    detailFormat: "Comedy commentary/conversation about cultural conspiracy theories",
    season: "2026",
    videoPath: null as string | null,
    oneSheetPath: null as string | null,
    demo: "18–35 · Mixed",
    thumbnailPath: "/thumbnails/so-true.jpg",
    slateImagePath: "/assets/Images/Slate/Slides BG_My Momma Told Me.jpg",
    talent: "Langston Kerman & David Gborie",
    youtubeUrl: "https://www.youtube.com/@MyMommaToldMe",
    audioUrl: "https://open.spotify.com/show/4k3gmSWsZRadfpgyLNcG9B",
    audience: {
      followers: "128K",
      monthlyViews: "3.7M",
      ages: [
        { label: "13–17", pct: 0.30 },
        { label: "18–24", pct: 4.70 },
        { label: "25–34", pct: 52.40 },
        { label: "35–44", pct: 35.80 },
        { label: "45–54", pct: 6.30 },
        { label: "55–64", pct: 0.40 },
        { label: "65+", pct: 0.10 },
      ],
    },
  },
];

/* =========================================================
   PAGE
   ========================================================= */
export default async function LandingPage() {
  const cookieStore = await cookies();

  if (cookieStore.has("wave-auth")) {
    const email = cookieStore.get("wave-user")?.value ?? "";
    let user: { firstName: string; lastName: string; email: string; company: string; title: string } | undefined;
    if (email) {
      const { data } = await supabase
        .from("vip_accounts")
        .select("name, email, company, title")
        .eq("email", email)
        .maybeSingle();
      if (data) {
        const parts = (data.name ?? "").trim().split(/\s+/);
        user = {
          firstName: parts[0] ?? "",
          lastName: parts.slice(1).join(" "),
          email: data.email ?? email,
          company: data.company ?? "",
          title: data.title ?? "",
        };
      }
    }
    return <SlateCarousel shows={[...shows].sort((first, second) => Number(second.id === "ngl") - Number(first.id === "ngl"))} user={user} />;
  }

  redirect("/login");
}

